# Generated by Django 5.1.4 on 2025-01-08 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('platform', models.CharField(choices=[('LI', 'LinkedIn'), ('TW', 'Twitter'), ('IG', 'Instagram'), ('FB', 'Facebook')], max_length=2)),
                ('brand_voice', models.CharField(choices=[('PRO', 'Professional'), ('CAS', 'Casual'), ('HUM', 'Humorous'), ('EDU', 'Educational'), ('INS', 'Inspirational')], max_length=3)),
                ('target_audience', models.TextField()),
                ('content_topic', models.TextField()),
                ('call_to_action', models.CharField(blank=True, max_length=25)),
                ('key_points', models.TextField()),
                ('post_length', models.CharField(choices=[('S', 'Short'), ('M', 'Medium'), ('L', 'Long')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
