# Generated by Django 5.1.4 on 2025-01-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedpost',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='ai_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
